### PR TITLE
Add coveralls

### PR DESCRIPTION
**Pull request by seanwiseman**

### CODE REVIEW

**Comment by seanwiseman** [comment]
Awaiting merge of [https://github.com/elifesciences/builder-private/pull/74](url). After that I will loose Travis and change coveralls to use the access token.

**Comment by giorgiosironi** [comment]
Should be ready now:
```
elife@ci--libraries:~$ ls /etc/coveralls/tokens/ -l
total 28
-rw-r--r-- 1 root root 34 Nov  8 15:53 elife-api-validator
-rw-r--r-- 1 root root 34 Oct 31 17:29 elife-article
-rw-r--r-- 1 root root 34 Nov  8 15:53 elife-bus-sdk
-rw-r--r-- 1 root root 34 Oct 31 17:29 elife-crossref-xml-generation
-rw-r--r-- 1 root root 34 Oct 31 17:29 elife-poa-xml-generation
-rw-r--r-- 1 root root 34 Oct 31 17:29 elife-pubmed-xml-generation
-rw-r--r-- 1 root root 34 Oct 31 17:29 elife-tools
```

**Comment by giorgiosironi** [comment]
I couldn't remember how the pillar keys would get transformed into file names, but you don't necessarily have to prefix them with `elife`. So if you want to rename them later to the project names e.g. `bus-sdk-python` that would be more in line with the others.

**Comment by seanwiseman** [comment]
@giorgiosironi  OK to merge this now?

**Review by giorgiosironi — APPROVED** [review]

**Pull request merged**
